//This is autogenerated, don't edit the content!
//params: spr: 200 theta: 1.8 microstep: 16
#include "stdint.h"
#include "sin_lut_microstep_16.h"
const int8_t sin_lut[SIN_LUT_LEN] PROGMEM = {
0,12,25,37,49,60,70,80,90,98
,106,112,117,122,125,126,127,126,125,122
,117,112,106,98,90,81,71,60,49,37
,25,13,0,-12,-25,-37,-49,-60,-70,-80
,-90,-98,-106,-112,-117,-122,-125,-126,-127,-126
,-125,-122,-117,-112,-106,-98,-90,-81,-71,-60
,-49,-37,-25,-13};

