#ifndef TWI_COMMON_H
#define TWI_COMMON_H


typedef enum{
    CMD_MOTOR_STEP_CW = 0x1,
    CMD_MOTOR_STEP_CCW = 0x2,
    CMD_MOTOR_RUN_CW = 0x3,
    CMD_MOTOR_RUN_CCW = 0x4,
    CMD_MOTOR_STOP = 0x5,
    CMD_MOTOR_POWEROFF = 0x6,
    CMD_MOTOR_SYNC = 0x7,
    CMD_MOTOR_RELEASE = 0x8
}MasterCMD;

typedef enum{
    MOTOR_STATUS_UNKNOWN = 0,
    MOTOR_STATUS_ERROR = 1,
    MOTOR_STATUS_IDLE = 2,
    MOTOR_STATUS_BUSY = 3,
    MOTOR_STATUS_ENDSTOP_1 = 4,
    MOTOR_STATUS_ENDSTOP_2 = 5,
    MOTOR_STATUS_COUNT
}sMotorState;

enum{
    CMD_FIRMWARE_NONE = 0,
    CMD_FIRMWARE_SENSOR_DIAG,
    CMD_FIRMWARE_MOTOR_STATUS,
    CMD_FIRMWARE_RESET
};

enum{
    TWI_RX_ADDR_CMD = 0,
    TWI_RX_ADDR_STEPS = 1,
    TWI_RX_ADDR_RPM = 3,
    TWI_RX_ADDR_CMD_FIRMWARE = 4
};
enum{
    TWI_TX_ADDR_SENSOR_RAW = 0,
    TWI_TX_ADDR_SENSOR_DIAG1 = 2,
    TWI_TX_ADDR_SENSOR_DIAG2 = 4,
    TWI_TX_ADDR_MOTOR_STATUS = 5,
    TWI_TX_ADDR_FIRMWARE_VERSION = 6
};


#endif /*TWI_COMMON_H*/